{
 "title": "App - Basic",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut). Data from prometheus (which auto install by istio service-mesh on Kubernetes)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, namespace)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\", namespace=\"$namespace\", area=\"heap\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\", namespace=\"$namespace\", area=\"nonheap\"},id)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{application=~\"$application\"}, version)"
    }
   }
  ]
 },
 "panels": [
  { "title": "I/O Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(base_REST_request_total[1h])",
     "legendFormat": "{{class}} __ {{method}}"
    }
   ]
  },
  {
   "title": "Prime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(application_com_luizalabs_PrimeNumberChecker_checksTimer_seconds_count[1m]))",
     "legendFormat": "Prime"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{}[1m]))/sum(rate(application_com_luizalabs_PrimeNumberChecker_checksTimer_seconds_count{}[1m]))"
    },
    {
     "expr": "max(application_com_luizalabs_PrimeNumberChecker_checksTimer_max_seconds{})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vendor_agroal_active_count", "legendFormat": "Connections" }
   ]
  }
 ]
}